sudo: required
language: generic
services:
  - docker

before_install:
  - sudo docker build -t washablealt/react-test:v1 -f ./client/Dockerfile.dev ./client

script:
  # previously - docker run washable-alt/react-test npm test -- --coverage
  - sudo docker run -e CI=true washablealt/react-test npm test
  
after_success:
  - sudo docker build -t multi-client:v1 ./client
  - sudo docker build -t multi-nginx:v1 ./nginx
  - sudo docker build -t multi-server:v1 ./server
  - sudo docker build -t multi-worker:v1 ./worker

  # Log in to docker CLI
  - sudo echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - sudo docker tag multi-client:v1 washablealt/multi-client:v1
  - sudo docker tag multi-nginx:v1 washablealt/multi-nginx:v1
  - sudo docker tag multi-server:v1 washablealt/multi-server:v1
  - sudo docker tag multi-worker:v1 washablealt/multi-worker:v1
  - sudo docker push washablealt/multi-client:v1
  - sudo docker push washablealt/multi-nginx:v1
  - sudo docker push washablealt/multi-server:v1
  - sudo docker push washablealt/multi-worker:v1
  - sudo docker push washablealt/react-test:v1
