sudo: required
language: generic
services:
  - docker

before_install:
  - sudo docker build -t washable-alt/react-test -f ./client/Dockerfile.dev ./client

script:
  # previously - docker run washable-alt/react-test npm test -- --coverage
  - sudo docker run -e CI=true washable-alt/react-test npm test
  
after_success:
  - sudo docker build -t washable-alt/multi-client ./client
  - sudo docker build -t washable-alt/multi-nginx ./nginx
  - sudo docker build -t washable-alt/multi-server ./server
  - sudo docker build -t washable-alt/multi-worker ./worker

  # Log in to docker CLI
  - sudo echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - sudo docker push washable-alt/multi-client
  - sudo docker push washable-alt/multi-nginx
  - sudo docker push washable-alt/multi-server
  - sudo docker push washable-alt/multi-worker