sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t washable-alt/react-test -f ./client/Dockerfile.dev

script:
  # previously - docker run -e CI=true washable-alt/react-test npm test
  - docker run washable-alt/react-test npm test -- --coverage

after_success:
  - docker build -t washable-alt/multi-client ./client
  - docker build -t washable-alt/multi-nginx ./nginx
  - docker build -t washable-alt/multi-server ./server
  - docker build -t washable-alt/multi-worker ./worker
