sudo: required
language: generic
services:
  - docker

before_install:
  - sudo docker build -t washablealt/react-test -f ./client/Dockerfile.dev ./client

script:
  # previously - docker run washable-alt/react-test npm test -- --coverage
  - sudo docker run -e CI=true washablealt/react-test npm test
  
after_success:
  - sudo docker build -t washablealt/multi-client ./client
  - sudo docker build -t washablealt/multi-nginx ./nginx
  - sudo docker build -t washablealt/multi-server ./server
  - sudo docker build -t washablealt/multi-worker ./worker

  # Log in to docker CLI
  - sudo echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - sudo docker tag washablealt/multi-client:firstimagepush washablealt/multi-docker:multi-client
  - sudo docker tag washablealt/multi-nginx:firstimagepush washablealt/multi-docker:multi-nginx
  - sudo docker tag washablealt/multi-server:firstimagepush washablealt/multi-docker:multi-server
  - sudo docker tag washablealt/multi-worker:firstimagepush washablealt/multi-docker:multi-worker
  - sudo docker push washablealt/multi-docker:multi-client
  - sudo docker push washablealt/multi-docker:multi-nginx
  - sudo docker push washablealt/multi-docker:multi-server
  - sudo docker push washablealt/multi-docker:multi-worker