sudo: required
services:
  - docker

before_install:
  - docker build -t washable-alt/react-test -f ./client/Dockerfile.dev ./client

script:
  # previously - docker run -e CI=true washable-alt/react-test npm test
  - docker run washable-alt/react-test npm test -- --coverage

after_success:
  - docker build -t washable-alt/multi-client ./client
  - docker build -t washable-alt/multi-nginx ./nginx
  - docker build -t washable-alt/multi-server ./server
  - docker build -t washable-alt/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push washable-alt/multi-client
  - docker push washable-alt/multi-nginx
  - docker push washable-alt/multi-server
  - docker push washable-alt/multi-worker